[package]
name = "aptos-dictionary-contract"
version = "1.0.0"
authors = []

[addresses]
aptos_dictionary_contract = "924a57c844cee4f0733134ecaf57bd82145df9a472f46940c558100a036e1908"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
